name: "SyncLyrics (UDP Only)"
version: "0.0.45"
slug: synclyrics_udp
description: "Real-time synchronized lyrics from UDP audio input."
url: "https://github.com/baileyboy0304/SyncLyricsUDP"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true
map:
  - addon_config:rw
init: false
options:
  music_assistant_base_url: ""
  music_assistant_token: ""
  music_assistant_player_id: ""
  lastfm_api_key: ""
  server_port: 9012
  https_enabled: true
  https_port: 9013
  recognition_enabled: true
  udp_listen_port: 6056
  udp_audio_sample_rate: 16000
  udp_jitter_buffer_ms: 60
  players: []
  players_auto_discover: true
schema:
  music_assistant_base_url: str?
  music_assistant_token: str?
  music_assistant_player_id: str?
  lastfm_api_key: str?
  server_port: port
  https_enabled: bool
  https_port: port
  recognition_enabled: bool
  udp_listen_port: port
  udp_audio_sample_rate: "int(8000,48000)"
  udp_jitter_buffer_ms: "int(0,500)"
  players:
    - name: str
      source_ip: str?
      rtp_ssrc: str?
      music_assistant_player_id: str?
      description: str?
  players_auto_discover: bool
